In [203]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline,make_pipeline

In [204]:
df = pd.read_csv("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/data/raw/kaggle_diabetes.csv")
df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.127   47        1  
1                     0.233   23        0

In [205]:
import pandas as pd

file_path = "data/raw/kaggle_diabetes.csv"

try:
    df = pd.read_csv(file_path)
    print(df.head(2))
except FileNotFoundError:
    print(f"File '{file_path}' not found.")


File 'data/raw/kaggle_diabetes.csv' not found.


# Lets make a pipeline for standardizing the data


In [206]:
from sklearn.preprocessing import StandardScaler

In [207]:
X = df.drop(columns='Outcome',axis=1)
y = df['Outcome']

In [208]:
X.shape,y.shape

((2000, 8), (2000,))

In [209]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Assuming 'X' and 'y' are already defined
# Define the steps of the pipeline
pipeline = Pipeline(steps=[
    ('scaler', StandardScaler())  # StandardScaler is used as an example step
])

In [210]:
X.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   

   DiabetesPedigreeFunction  Age  
0                     0.127   47  
1                     0.233   23

In [211]:
from sklearn.compose import ColumnTransformer

In [212]:
p1 = ColumnTransformer([('cols',pipeline,X.columns)])

In [213]:
X = p1.fit_transform(X)

In [214]:
X[0]

array([-0.5153943 ,  0.52455322, -0.37248123,  0.87364499, -0.72201552,
        0.17268332, -1.06324616,  1.18042417])

In [215]:
X = pd.DataFrame(X)

In [216]:
X.head(2)

0         1         2         3         4         5         6  \
0 -0.515394  0.524553 -0.372481  0.873645 -0.722016  0.172683 -1.063246   
1 -1.120495 -1.159756  0.670080  0.625186  0.402563  0.737249 -0.735551   

          7  
0  1.180424  
1 -0.856326

In [217]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

def transform_data(X):
    pipeline = Pipeline(steps=[
    ('scaler', StandardScaler())])
    p1 = ColumnTransformer([('cols',pipeline,X.columns)])
    X = p1.fit_transform(X)
    print(X[0])
    X = pd.DataFrame(X)
    return X

In [218]:
transform_data(X)

[-0.5153943   0.52455322 -0.37248123  0.87364499 -0.72201552  0.17268332
 -1.06324616  1.18042417]


0         1         2         3         4         5         6  \
0    -0.515394  0.524553 -0.372481  0.873645 -0.722016  0.172683 -1.063246   
1    -1.120495 -1.159756  0.670080  0.625186  0.402563  0.737249 -0.735551   
2    -1.120495  0.742890 -3.604422 -1.300374 -0.722016  1.473638  0.491759   
3    -1.120495  0.430980 -0.059713  1.308449  1.527142  1.240448 -0.327478   
4    -0.817945  0.555744 -0.372481  1.246334  3.596367  1.044077  0.201161   
...        ...       ...       ...       ...       ...       ...       ...   
1995 -0.515394 -1.440474 -0.268225  0.190382 -0.227201 -0.305970 -0.312021   
1996  1.299907  1.803381  0.148800  1.308449  0.447546  0.062225  0.766899   
1997  0.694807 -1.128565  0.461568 -1.300374 -0.722016 -0.121872 -0.274924   
1998 -1.120495  0.243835  2.129667  1.556908  0.447546  4.284191 -0.469686   
1999 -0.515394 -1.253329  0.148800 -0.368651 -0.038272 -0.256877  0.235167   

             7  
0     1.180424  
1    -0.856326  
2    -0.177409  
3    -0.771462  
4    -1.026055  
...        ...  
1995 -0.007680  
1996  0.246914  
1997  0.756101  
1998 -0.601732  
1999 -0.686597  

[2000 rows x 8 columns]

In [333]:
pickle.dump(p1,open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/p1.pkl","wb"))

In [219]:
import pickle
model = pickle.load(open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/ann_model.h5","rb"))

In [249]:
data_array = [[2,138,62,35,0,33.6,0.127,47	]]
data = pd.DataFrame(data_array,columns=['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'])
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   

   DiabetesPedigreeFunction  Age  
0                     0.127   47

In [261]:
data2 = X.iloc[1:2]
data2
type(data2)

pandas.core.frame.DataFrame

In [250]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

def transform_data(X):
    pipeline = Pipeline(steps=[
    ('scaler', StandardScaler())])
    p1 = ColumnTransformer([('cols',pipeline,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'])])
    X = p1.fit_transform(X)
    type(X)
    print(X[0])
    X = pd.DataFrame(X)
    type(X)
    return X

In [251]:
p1_load = pickle.load(open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/p1.pkl", "rb"))

In [252]:
transform_data(data)

[0. 0. 0. 0. 0. 0. 0. 0.]


0    1    2    3    4    5    6    7
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [279]:
mm=p1_load.transform(data)


In [280]:
cu = p1_load.transform(data)
tdata = pd.DataFrame(cu)

In [281]:
prd = model.predict(tdata)
# dk = int(prd[0])
# print(kk)
# if kk == 1:
#     print("Sorry! you have Diabetic")
# else:
#     print("Great! you dont have Diabetic")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step


In [274]:
u=int(prd[0])
print(u)

0


/var/folders/15/vc_j9b113v12tq235z56lnpr0000gn/T/ipykernel_56528/4103226795.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  u=int(prd[0])


In [223]:
type(data)

pandas.core.frame.DataFrame

In [275]:
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   

   DiabetesPedigreeFunction  Age  
0                     0.127   47

In [277]:
dn = model.predict(data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step


In [278]:
if dn == 1:
    print("Sorry! you have Diabetic")
else:
    print("Great! you dont have Diabetic")

Sorry! you have Diabetic


In [295]:
cu = p1_load.transform(data)
tdata = pd.DataFrame(cu,columns=['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'])
tdata.head()
prd = model.predict(tdata)
my_prd = int(prd[0])
if my_prd == 1:
    print("Sorry! you have Diabetic")
else:
    print("Great! you dont have Diabetic")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step
Great! you dont have Diabetic


/var/folders/15/vc_j9b113v12tq235z56lnpr0000gn/T/ipykernel_56528/355273647.py:5: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  my_prd = int(prd[0])


In [294]:
tdata

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0    -0.515394  0.524553      -0.372481       0.873645 -0.722016  0.172683   

   DiabetesPedigreeFunction       Age  
0                 -1.063246  1.180424

In [297]:
a = StandardScaler()
pickle.dump(a,open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/sc.pkl","wb"))

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   

   DiabetesPedigreeFunction  Age  
0                     0.127   47

In [303]:
scmodel = pickle.load(open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/sc.pkl","rb"))

In [329]:
scmodel = pickle.load(open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/sc.pkl","rb"))
kdaq = scmodel.fit_transform(data2)
dt = pd.DataFrame(kdaq)
my_prediction_proba = model.predict(dt)
my_prediction = (my_prediction_proba >= 0.7).astype(int)
my_prd1 = int(my_prediction[0])
if my_prd1 == 1:
    print("Sorry! you have Diabetic")
else:
    print("Great! you dont have Diabetic")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
Sorry! you have Diabetic


/var/folders/15/vc_j9b113v12tq235z56lnpr0000gn/T/ipykernel_56528/550477481.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  my_prd1 = int(my_prediction[0])


In [331]:
data2

0         1        2         3         4         5         6  \
1 -1.120495 -1.159756  0.67008  0.625186  0.402563  0.737249 -0.735551   

          7  
1 -0.856326

In [332]:
kdaq

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [334]:
ct_ld = pickle.load(open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/p1.pkl","rb"))

In [335]:
df.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   
1            0       84             82             31      125  38.2   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.127   47        1  
1                     0.233   23        0

In [336]:
d1 = df.drop(columns='Outcome',axis=1).iloc[0:1]
d2 = df.drop(columns='Outcome',axis=1).iloc[1:2]

In [337]:
d1

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            2      138             62             35        0  33.6   

   DiabetesPedigreeFunction  Age  
0                     0.127   47

In [338]:
d2

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1            0       84             82             31      125  38.2   

   DiabetesPedigreeFunction  Age  
1                     0.233   23

In [340]:
col = d1.columns

In [343]:
t_data = ct_ld.transform(d1)

t_data

array([[-0.5153943 ,  0.52455322, -0.37248123,  0.87364499, -0.72201552,
         0.17268332, -1.06324616,  1.18042417]])

In [347]:
m_load = pickle.load(open("/Users/bhikipallai/Desktop/Projects/Machine_Learning_Projects/saved_models/xgb_model.pkl","rb"))

In [348]:
m_load.predict(t_data)

array([1])

In [349]:
d2_tr_data = ct_ld.transform(d2)
m_load.predict(d2_tr_data)

array([0])